# Site settings
title: Falmouth University UI Library
email: aaron.marr@falmouth.ac.uk
description: "A UI library for creating beautiful Web app interfaces."
baseurl: ""
url: "http://ucfalmouth.github.io/fu-ui"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty
